-- Disable unused self warnings.
self = false

std = "lua51+wow+wowstd"

max_line_length = false

exclude_files = {
    ".luacheckrc",
    "Interface/AddOns/nPlates",
    "Interface/AddOns/oUF",
    "Interface/AddOns/oUF_Neav/modules/oUF_MovableFrames",
    "Interface/AddOns/oUF_NeavRaid/modules/CallbackHandler-1.0",
    "Interface/AddOns/oUF_NeavRaid/modules/LibSharedMedia-3.0",
    "Interface/AddOns/oUF_NeavRaid/modules/LibStub",
}

ignore = {
    "211/_.*", -- Unused local variable starting with _
    "212", -- unused argument
    "542", -- empty if branch
    "432", -- shadowing upvalue argument
}

globals = {
    -- Third-party addons and libraries.
    "DBM",
    "DBT",
    "Grid2LayoutFrame",
    "GridLayoutFrame",
    "LibStub",
    "NumerationFrame",
    "Omen",
    "OmenBarList",
    "PSFmain1",
    "PSFmain2",
    "PSFmain3",
    "Recount",
    "Skada",
    "SkadaBarWindowSkada",
    "oUF",
    "tdpsFrame",
    "Numeration",
    "AtlasLoot",
    "AltoholicFrame",
    "_detalhes",
    "BigWigsOptions",

    -- !NeavOptions.
    "NeavOptionsDB",
    "NeavOptions_Register",
    "SLASH_NEAVOPTIONS1",
    "SLASH_NEAVOPTIONS2",

    -- !Colorz.
    "Colorz_GetUnitColor",

    -- nCore.
    "SLASH_ACTIONCAM1",
    "SLASH_AlertFrameAnchor_AnchorToggle1",
    "SLASH_RELOADUI1",
    "nCoreDB",
    "nCore_OnEvent",
    "nCore_OnLoad",

    -- nMainbar.
    "nMainbar_ToggleBags",
    "SLASH_GM1",
    "SLASH_GM2",
    "SLASH_GM3",

    -- nMinimap.
    "FriendsScrollFrame",
    "GuildScrollFrame",
    "MemoryScrollFrame",
    "BagsShown",
    "nMinimapDifficulty",
    "nMinimapDifficulty_OnLoad",
    "nMinimapTab",
    "nMinimapTab_Friends_OnEvent",
    "nMinimapTab_Friends_ShowTooltip",
    "nMinimapTab_Friends_UpdateScrollFrame",
    "nMinimapTab_Guild_OnEvent",
    "nMinimapTab_Guild_ShowTooltip",
    "nMinimapTab_Guild_UpdateScrollFrame",
    "nMinimapTab_HideTab",
    "nMinimapTab_Info_ShowTooltip",
    "nMinimapTab_Memory_UpdateScrollFrame",
    "nMinimapTab_OnLoad",
    "nMinimapTab_OnUpdate",
    "nMinimapTab_ShowTab",
    "nMinimap_UpdateFriendButton",
    "nMinimap_UpdateFriends",
    "nMinimap_UpdateGuildButton",
    "nMinimap_UpdateGuildMembers",
    "nMinimap_UpdateMemory",
    "nMinimap_UpdateMemoryButton",
    "SLASH_nBag_Toggle1",

    -- nPower.
    "nPower_OnEvent",
    "nPower_OnLoad",

    -- nTooltip
    "SLASH_nTooltip_AnchorToggle1",

    -- oUF_Neav
    "SLASH_oUF_Neav_Castbar_AnchorToggle1",
    "SLASH_oUF_Neav_Reset1",
    "oUF_NeavDB",
    "oUF_Neav_Player",

    -- oUF_NeavRaid.
    "NeavRaid_OnEvent",
    "NeavRaid_OnLoad",
    "SLASH_oUF_Neav_Raid_AnchorToggle1",
    "nRaidDB",
}

stds.wowstd = {
    read_globals = {
        "abs",
        "ceil",
        "find",
        "floor",
        "format",
        "gsub",
        "hooksecurefunc",
        "max",
        "min",
        "mod",
        "securecall",
        "strsplit",
        string = {
            fields = {"split"}
        },
        "sub",
        "tinsert",
        "tremove",
        "wipe",
    }
}

stds.wow = {
    globals = {
        "GetMinimapShape",
        "SlashCmdList",
        "StaticPopupDialogs",
    },
    read_globals = {
        C_ActionBar = {
            fields = {
                "HasExtraActionBar",
                "IsEquippedAction",
                "IsUsableAction",
            }
        },
        C_AddOns = {
            fields = {
                "GetAddOnInfo",
                "GetAddOnMetadata",
                "GetNumAddOns",
                "IsAddOnLoaded",
                "LoadAddOn",
            }
        },
        C_BattleNet = {
            fields = {
                "GetFriendAccountInfo",
            }
        },
        C_CVar = {
            fields = {
                "GetCVar",
            }
        },
        C_ClassColor = {
            fields = {
                "GetClassColor",
            }
        },
        C_ColorUtil = {
            fields = {
                "WrapTextInColor",
            }
        },
        C_CurveUtil = {
            fields = {
                "CreateCurve",
            }
        },
        C_DateAndTime = {
            fields = {
                "GetCurrentCalendarTime",
            }
        },
        C_FriendList = {
            fields = {
                "GetFriendInfoByIndex",
                "GetNumFriends",
                "GetNumOnlineFriends",
            }
        },
        C_GossipInfo = {
            fields = {
                "GetActiveQuests",
                "GetAvailableQuests",
                "SelectActiveQuest",
                "SelectAvailableQuest",
            }
        },
        C_GuildInfo = {
            fields = {
                "GetMOTD",
                "GuildRoster",
            }
        },
        C_Item = {
            fields = {
                "GetItemQualityByID",
                "GetItemQualityColor",
                "GetItemSubClassInfo",
                "IsEquippedItemType",
            }
        },
        C_Map = {
            fields = {
                "GetBestMapForUnit",
                "GetWorldPosFromMapPos",
            }
        },
        C_MerchantFrame = {
            fields = {
                "GetItemInfo",
            }
        },
        C_PartyInfo = {
            fields = {
                "ConvertToParty",
                "ConvertToRaid",
                "DoReadyCheck",
                "InviteUnit",
            }
        },
        C_PlayerInteractionManager = {
            fields = {
                "IsReplacingUnit",
            }
        },
        C_PvP = {
            fields = {
                "GetZonePVPInfo",
            }
        },
        C_QuestLog = {
            fields = {
                "GetLogIndexForQuestID",
                "GetMaxNumQuestsCanAccept",
                "GetNumQuestLogEntries",
            }
        },
        C_ResearchInfo = {
            fields = {
                "GetDigSitesForMap",
            }
        },
        C_SpecializationInfo = {
            fields = {
                "GetInspectSpecialization",
                "GetSpecialization",
                "GetSpecializationInfo",
            }
        },
        C_Spell = {
            fields = {
                "GetSpellCooldown",
            }
        },
        C_StringUtil = {
            fields = {
                "TruncateWhenZero",
                "WrapString",
            }
        },
        C_Timer = {
            fields = {
                "After",
                "NewTicker",
            }
        },
        C_VignetteInfo = {
            fields = {
                "GetVignetteInfo",
            }
        },
        "ADDONS",
        "ALTERNATE_POWER_INDEX",
        "AbbreviateNumbers",
        "AcceptQuest",
        "AchievementCriteriaFont",
        "AchievementDateFont",
        "AchievementDescriptionFont",
        "AchievementPointsFont",
        "AchievementPointsFontSmall",
        "AddonList",
        "AlertFrame",
        "AuraContainerSortMethod",
        "AuraUtil",
        "AutoCompleteBox",
        "AutoEquipCursorItem",
        "BNET_CLIENT_WOW",
        "BNGetNumFriendInvites",
        "BNGetNumFriends",
        "BNToastFrame",
        "BN_INLINE_TOAST_FRIEND_PENDING",
        "BNet_GetClientEmbeddedTexture",
        "BNet_GetValidatedCharacterName",
        "BOSS",
        "BackdropTemplateMixin",
        "BagsBar",
        "BattlePetTooltip",
        "BuffFrame",
        "BuyMerchantItem",
        "CALENDAR_FILTER_RAID_LOCKOUTS",
        "CANCEL",
        "CHATLOGDISABLED",
        "CHATLOGENABLED",
        "CHAT_FLAG_AFK",
        "CHAT_FRAMES",
        "CHAT_FRAME_TAB_NORMAL_MOUSEOVER_ALPHA",
        "CHAT_FRAME_TAB_NORMAL_NOMOUSE_ALPHA",
        "CHAT_MSG_AFK",
        "COMBATLOG",
        "COMBATLOGDISABLED",
        "COMBATLOGENABLED",
        "COMBAT_MISC_INFO",
        "COMPACT_UNIT_FRAME_PROFILE_DISPLAYMAINTANKANDASSIST",
        "COMPACT_UNIT_FRAME_PROFILE_DISPLAYPOWERBAR",
        "CONVERT_TO_PARTY",
        "CONVERT_TO_RAID",
        "CVarCallbackRegistry",
        "CanInspect",
        "CanScanResearchSite",
        "CharacterLevelText",
        "ChatAlertFrame",
        "ChatFrame1",
        "ChatFrame1EditBox",
        "ChatFrame1Tab",
        "ChatFrame2",
        "ColorPickerFrame",
        "ChatFrameChannelButton",
        "ChatFrameMenuButton",
        "ChatFrameToggleVoiceDeafenButton",
        "ChatFrameToggleVoiceMuteButton",
        "ChatFrameUtil",
        "ChatTypeInfo",
        "ClearInspectPlayer",
        "ClearOverrideBindings",
        "ClearRaidMarker",
        "CloseQuest",
        "CompleteQuest",
        "ConfirmAcceptQuest",
        "ConsoleExec",
        "Constants",
        "CreateAtlasMarkup",
        "CopyTable",
        "CreateColor",
        "CreateFrame",
        "CreateTextureMarkup",
        "CreateVector2D",
        "CursorHasItem",
        "CurveConstants",
        "DAMAGER",
        "DEAD",
        "DEFAULT",
        "DEFAULT_CHAT_FRAME",
        "DEFAULT_DND_MESSAGE",
        "DEFAULT_READY_CHECK_STAY_TIME",
        "DURABILITY",
        "DebuffFrame",
        "DressUpFrame",
        "DressUpFrameCancelButton",
        "DressUpFrameResetButton",
        "DurabilityFrame",
        "ELITE",
        "ERR_INVITE_PLAYER_S",
        "EmbeddedItemTooltip",
        "Enum",
        "EnumerateFrames",
        "EventRegistry",
        "ExpansionLandingPageMinimapButton",
        "ExtraActionBarFrame",
        "FACTION_BAR_COLORS",
        "FOCUS",
        "FRIENDS_BNET_NAME_COLOR",
        "FRIENDS_BUTTON_TYPE_BNET",
        "FRIENDS_BUTTON_TYPE_WOW",
        "FRIENDS_LIST_ONLINE",
        "FloatingBattlePetTooltip",
        "FloatingGarrisonFollowerTooltip",
        "FloatingPetBattleAbilityTooltip",
        "FocusFrame",
        "FriendsTooltip",
        "GAMETIME_TOOLTIP_TOGGLE_CLOCK",
        "GMChatFrame",
        "GROUP",
        "GUILD_MEMBERS_ONLINE_COLON",
        "GUILD_MOTD",
        "GameFontDisable",
        "GameFontDisableSmall",
        "GameFontHighlight",
        "GameFontHighlightExtraSmall",
        "GameFontHighlightMedium",
        "GameFontHighlightSmall",
        "GameFontNormal",
        "GameFontNormalHuge",
        "GameFontNormalSmall",
        "GameTimeCalendarEventAlarmTexture",
        "GameTimeCalendarInvitesGlow",
        "GameTimeCalendarInvitesTexture",
        "GameTimeFrame",
        "GameTime_UpdateTooltip",
        "GameTooltip",
        "GameTooltip_Hide",
        "GameTooltip_SetDefaultAnchor",
        "GameTooltipHeaderText",
        "GameTooltipStatusBar",
        "GameTooltipText",
        "GameTooltipTextLeft1",
        "GameTooltipTextLeft2",
        "GameTooltipTextSmall",
        "GameTooltip_InsertFrame",
        "GameTooltip_UnitColor",
        "GetActiveTitle",
        "GetAddOnMemoryUsage",
        "GetAutoQuestPopUp",
        "GetAvailableBandwidth",
        "GetBindingKey",
        "GetCVarBool",
        "GetCreatureDifficultyColor",
        "GetDifficultyInfo",
        "GetDownloadedPercentage",
        "GetGuildInfo",
        "GetGuildRosterInfo",
        "GetInstanceInfo",
        "GetInventoryItemDurability",
        "GetLocale",
        "GetLootRollItemInfo",
        "GetLootSpecialization",
        "GetMaxLevelForPlayerExpansion",
        "GetMerchantItemMaxStack",
        "GetMouseFoci",
        "GetNetIpTypes",
        "GetNetStats",
        "GetNumActiveQuests",
        "GetNumAutoQuestPopUps",
        "GetNumAvailableQuests",
        "GetNumGroupMembers",
        "GetNumGuildMembers",
        "GetNumLootItems",
        "GetNumQuestChoices",
        "GetNumSavedInstances",
        "GetNumSavedWorldBosses",
        "GetPVPTimer",
        "GetQuestDifficultyColor",
        "GetQuestMoneyToGet",
        "GetQuestReward",
        "GetRaidRosterInfo",
        "GetRaidTargetIndex",
        "GetRealZoneText",
        "GetRealmName",
        "GetRuneCooldown",
        "GetSavedInstanceInfo",
        "GetSavedWorldBossInfo",
        "GetSpecializationInfoForSpecID",
        "GetSubZoneText",
        "GetThreatStatusColor",
        "GetTime",
        "GossipFrame",
        "HEALER",
        "HOME",
        "HelpOpenWebTicketButton",
        "HideUIPanel",
        "ICON_LIST",
        "INVITE",
        "ITEM_VENDOR_STACK_BUY",
        "InCombatLockdown",
        "InitiateRolePoll",
        "InspectFrame",
        "IsAltKeyDown",
        "IsInGuild",
        "IsInInstance",
        "IsInRaid",
        "IsPVPTimerRunning",
        "IsQuestCompletable",
        "IsResting",
        "IsShiftKeyDown",
        "ItemRefShoppingTooltip1",
        "ItemRefShoppingTooltip2",
        "ItemRefTooltip",
        "LFG_LIST_ROLE_CHECK",
        "LOCALIZED_CLASS_NAMES_FEMALE",
        "LOCALIZED_CLASS_NAMES_MALE",
        "LibDBIconTooltip",
        "LibItemUpdateInfoTooltip",
        "LoggingChat",
        "LoggingCombat",
        "MAINMENUBAR_BANDWIDTH_LABEL",
        "MAINMENUBAR_DOWNLOAD_PERCENT_LABEL",
        "MAINMENUBAR_PROTOCOLS_LABEL",
        "MAINMENU_BUTTON",
        "MAP_AND_QUEST_LOG",
        "MAX_BOSS_FRAMES",
        "MAX_TOTEMS",
        "MOUSE_LABEL",
        "MainActionBar",
        "MainMenuMicroButton",
        "Menu",
        "MenuUtil",
        "MerchantFrame",
        "MerchantRepairText",
        "MicroMenuContainer",
        "Minimap",
        "MinimapCluster",
        "MinimapCompassTexture",
        "MinimapCompassTextureUnderlay",
        "MirrorTimerContainer",
        "Mixin",
        "MultiBar5",
        "MultiBar6",
        "MultiBar7",
        "MultiBarBottomLeft",
        "MultiBarBottomRight",
        "MultiBarLeft",
        "MultiBarRight",
        "NORMAL_FONT_COLOR",
        "NUM_OVERRIDE_BUTTONS",
        "NotifyInspect",
        "NumberFontNormal",
        "OptionsLabel",
        "OverrideActionBar",
        "PET_TYPE_SUFFIX",
        "PLAYER",
        "PLAYER_OFFLINE",
        "PVP_ENABLED",
        "PaperDollFrame",
        "PetActionBar",
        "PixelUtil",
        "PlaySound",
        "PossessActionBar",
        "PowerBarColor",
        "QuestFrame",
        "QuestFrameGreetingPanel",
        "QuestGetAutoAccept",
        "QuestScrollFrame",
        "QuickJoinToastButton",
        "RAID_CLASS_COLORS",
        "RAID_INFO_WORLD_BOSS",
        "RANGE_INDICATOR",
        "READY_CHECK",
        "RED_FONT_COLOR",
        "REMOVE",
        "REMOVE_WORLD_MARKERS",
        "REQUIRES_RELOAD",
        "RaidWarningFrame",
        "RegisterStateDriver",
        "ReloadUI",
        "ReputationBarMixin",
        "RollOnLoot",
        "SELECTED_CHAT_FRAME",
        "SOUNDKIT",
        "SPEC_PALADIN_RETRIBUTION",
        "SPELL_FAILED_BAD_TARGETS",
        "STANDARD_TEXT_FONT",
        "STOPWATCH_TITLE",
        "SelectActiveQuest",
        "SelectAvailableQuest",
        "SetBinding",
        "SetCVar",
        "SetOverrideBindingClick",
        "Settings",
        "ShoppingTooltip1",
        "ShoppingTooltip2",
        "ShowQuestComplete",
        "SlashCmdList",
        "StanceBar",
        "StaticPopup_Hide",
        "StaticPopup_Show",
        "StatusTrackingBarInfo",
        "StatusTrackingBarManager",
        "Stopwatch_Toggle",
        "TANK",
        "TOOLTIP_UNIT_LEVEL",
        "TOTAL_MEM_MB_ABBR",
        "TargetFrame",
        "TextStatusBarText",
        "TicketStatusFrame",
        "TicketStatusFrameButton",
        "TimeManagerAlarmFiredTexture",
        "TimeManagerClockButton",
        "TimeManagerClockTicker",
        "TimerTracker",
        "ToggleCharacter",
        "ToggleFrame",
        "ToggleHelpFrame",
        "TooltipDataProcessor",
        "UIErrorsFrame",
        "UIParent",
        "UIWidgetBelowMinimapContainerFrame",
        "UNKNOWN",
        "UNLOCK",
        "UnitAffectingCombat",
        "UnitBattlePetLevel",
        "UnitBattlePetType",
        "UnitCanAttack",
        "UnitChannelInfo",
        "UnitClass",
        "UnitClassification",
        "UnitCreatureType",
        "UnitDetailedThreatSituation",
        "UnitEffectiveLevel",
        "UnitExists",
        "UnitFactionGroup",
        "UnitFrame_OnEnter",
        "UnitFrame_OnLeave",
        "UnitGUID",
        "UnitGroupRolesAssigned",
        "UnitHasVehicleUI",
        "UnitHealth",
        "UnitHealthMax",
        "UnitHealthMissing",
        "UnitHealthPercent",
        "UnitInRaid",
        "UnitIsAFK",
        "UnitIsBattlePetCompanion",
        "UnitIsConnected",
        "UnitIsDND",
        "UnitIsDead",
        "UnitIsDeadOrGhost",
        "UnitIsEnemy",
        "UnitIsFriend",
        "UnitIsGhost",
        "UnitIsPVP",
        "UnitIsPVPFreeForAll",
        "UnitIsPlayer",
        "UnitIsSameServer",
        "UnitIsTapDenied",
        "UnitIsUnit",
        "UnitIsWildBattlePet",
        "UnitLevel",
        "UnitName",
        "UnitPVPName",
        "UnitPlayerControlled",
        "UnitPosition",
        "UnitPower",
        "UnitPowerMax",
        "UnitPowerMissing",
        "UnitPowerPercent",
        "UnitPowerType",
        "UnitRace",
        "UnitReaction",
        "UnitSelectionColor",
        "UnitThreatPercentageOfLead",
        "UnitThreatSituation",
        "UpdateAddOnMemoryUsage",
        "VOICEMACRO_2_Hu_1",
        "VehicleSeatIndicator",
        "WORLD",
        "WORLD_MARKER1",
        "WORLD_MARKER2",
        "WORLD_MARKER3",
        "WORLD_MARKER4",
        "WORLD_MARKER5",
        "WORLD_MARKER6",
        "WORLD_MARKER7",
        "WORLD_MARKER8",
        "WorldFrame",
        "WorldMapFrame",
        "WrapTextInColorCode",
        "YOU",
        "issecretvalue",
    }
}
